### PR TITLE
Add configuration for packages version

### PR DESCRIPTION
**Pull request by iustinam**
* allow installation of specific packages versions

### CODE REVIEW

**Comment by iustinam** [comment]
Could this feature be added ?

**Comment by iustinam** [comment]
@javierbertoli I fail to find that file or any other pkg states referring to salt packages..

**Comment by javierbertoli** [comment]
@iustinam, re: the `proxy.sls` file, ignore it. I grep'ed on a dirty local repo, and that file showed. My bad.

Re #314: I think both PRs complement each other: I agree that, usually, #314 will be enough. But that is true only if you use Saltstack's repo and want to pin the repo's version.

But even then, there are a few situations where your PR make sense, ie:

* You want to use the Saltstack's repo, but you want to pin packages so they're not upgraded without your control
* You have Saltstack's repo configured, but you want to use another version of the Salt packages, ie, thosse in the distro's repos.
* You have more than a single distro's repo configured (stable, testing, etc) and want to pin the package version to use.

@aboe76, wdyt? I'm OK with merging this PR.

**Comment by aboe76** [comment]
@javierbertoli I agree with your logic.

**Comment by iustinam** [comment]
I just added an example in pillar.example

**Comment by javierbertoli** [comment]
Thanks @iustinam & @aboe76

**Pull request merged**
