### PR TITLE
Add version check for minor pin

### PR DESCRIPTION
**Pull request by ralucasg**

### CODE REVIEW

**Comment by myii** [comment]
> @myii I remember testing it against some corner cases and getting some failures. Sadly it did not cross my mind to write it down and I don't quite remember when it was breaking. It might have been on the "Pin to Major Release" option since those links don't have 'archive/' in them or maybe on something else. I'm truly sorry I did not add my test results as a comment on the PR.

@ralucasg Thanks for your response.  The edge case was due to:

```jinja
{% if check_version|length > 1 %}
```

That would end up being applied for minor *and* major releases.  Changing that to `> 2` would be enough or like I did `>= 3`.

More importantly, I always prefer credit going to the person who has attempted to solve the problem.   Your solution was virtually there and I'd be happy to to switch out my PR #394 to revive your PR #365 again.  Or another way that could be done is that I supply your details to the commit in #394 so that the authorship goes back to you, which I can do by:

```bash
$ git commit --amend --author="Your Name <you@example.com>"
```

Let me know how you would like to proceed.  If you're not too bothered, we can just leave #394 as-is.

**Comment by myii** [comment]
@ralucasg Sorry, I don't mean for you to send your e-mail address here in GitHub.  In fact, I just realised I can use the anonymous GitHub-based address:

Raluca Samuilescu <ralucasg@users.noreply.github.com>.

I'll just do that and amend #394.

**Comment by myii** [comment]
@ralucasg OK, done.  If you see #394, you'll see the commit has your authorship.  Once the merge is complete, you'll be recognised as a contributor to this project.  Thank you for your bug report and your PR.

**Comment by ralucasg** [comment]
@myii Thank you so much, you didn't have to go that far as you added the correct solution and tested it so I believe you deserve the credits more than me. 
Also thank you for fixing the formula.

**Comment by myii** [comment]
@ralucasg You're welcome.

> ... as you added the correct solution and tested it so I believe you deserve the credits more than me.

Actually, it doesn't work like that.  If you had left this PR open, then this would have been the process:

1. Someone would have reviewed your code and suggested improvements or even the solution.
1. You would have made the changes and pushed them to this PR.
1. The PR would be merged, with the entire credit given to you.

So we've just recreated that here -- nothing extra.

**Pull request closed without merging**
