### PR TITLE
Switch config file.recurse to clean by default and tell it to ignore _*

### PR DESCRIPTION
**Pull request by iggy**
Salt writes it's schedule file to /etc/salt/{minion,master}.d/_schedule.conf

We don't want to stomp all over Salt's files, but we do want a pristine
starting point to lay down our managed config. So we use clean: True on the
file.recurse call, but we tell it to ignore files that start with an _

We have to rename the current config file (_defaults.conf) because it will be
ignored by the rule that ignores Salt's _* config files.

This also means we need to clean up old config files (_defaults.conf) and
restart the service if we cleaned it up.

### CODE REVIEW

**Comment by iggy** [comment]
Hopefully I didn't miss anything from #104

**Comment by aboe76** [comment]
@iggy why not rename the file to defaults.conf why f_defaults.conf?

**Comment by iggy** [comment]
I was just going for a short prefix (f_ "formula") that indicated that it was related to formulas. I don't feel particularly strongly about it.

**Comment by aboe76** [comment]
@iggy that's what I thought, and I think naming it override_defaults.conf is easier to figure out
in which file you need to look then f_defaults.conf

**Comment by iggy** [comment]
I'll wait and see what other people think. I'm not sure I like either option so far.

**Comment by iggy** [comment]
@gravyboat @nmadhok any preference on what to name the "default" conf file?

**Comment by gravyboat** [comment]
@iggy I'd say just name it override_defaults.conf for the sake of simplicity. I don't feel strongly about it one way or the other though. Let's see what Nitin thinks.

**Comment by nmadhok** [comment]
I don't think the naming really matters. override_defaults.conf perfectly works. Merging this one. Thanks @iggy @aboe76 and @gravyboat for the discussion!

**Comment by gravyboat** [comment]
@nmadhok The change hadn't been made when this was merged, it's still f_defaults. @iggy did you already have an update ready to go on this PR to update that name?

**Comment by nmadhok** [comment]
@gravyboat Like I said the name doesn't really matter. f_defaults.conf or override_defaults.conf both perfectly work.

**Comment by gravyboat** [comment]
@nmadhok Yeah I thought about it some more last night, and I think we should change it to something other than f_defaults.conf, because it sounds like 'fuck defaults'. @iggy am I grasping here?

**Comment by iggy** [comment]
I already said I'm not real fond of either. I was mostly being lazy when I did f_defaults.conf (but to give some context, it was actually formula_defaults.conf shortened).

**Comment by nmadhok** [comment]
@gravyboat Haha that's a good one! We can change it to another name. I don't mind :)

**Comment by gravyboat** [comment]
@nmadhok Yeah I just don't want it to become a standard, which then becomes a cringe inducing joke for years. @iggy I remember you saying what it was originally short for, just don't want it to be interpreted incorrectly.

**Comment by iggy** [comment]
I'll do whatever we decide on. Would like to get it done sooner rather than later so I don't have to clean up _2_ old config files.

**Comment by gravyboat** [comment]
@iggy Since no one really cares lets just make it override_defaults.conf, stays concise but can't be interpreted in certain ways.

**Comment by iggy** [comment]
So what does override mean exactly?

**Comment by aboe76** [comment]
@iggy this gets better and better...:) let's keep fuc_defaults.conf that should stir up a lot of conversation...

**Pull request merged**
