### PR TITLE
osmap: Raspbian used the Debian repo

### PR DESCRIPTION
**Pull request by alxwr**
According to https://repo.saltstack.com/#raspbian

Tested on Raspbian 9.

### CODE REVIEW

**Comment by myii** [comment]
@alxwr Thanks for this PR.  This will probably be merged as you've provided but I'm curious: aren't there any grains that match instead of using a literal `debian`?  Would you be as kind to paste the `grains.items` for the Raspbian?  Don't have one available and it would be great to have a reference of this.

**Comment by aboe76** [comment]
@myii the os_family grain on raspbian is 'Debian' but moving it to os_family map is bit diffictult because of the armhf processor

**Comment by myii** [comment]
@aboe76 Does that mean we can use something like this instead?

```yaml
{% set os_family_lower =  salt['grains.get']('os_family')|lower %}

...

Raspbian:
  pkgrepo: 'deb http://repo.saltstack.com/{{ py_ver_dir }}/{{ os_family_lower }}/{{ osmajorrelease }}/armhf/{{ salt_release }} {{ oscodename }} main'
  key_url: 'https://repo.saltstack.com/{{ py_ver_dir }}/{{ os_family_lower }}/{{ osmajorrelease }}/armhf/{{ salt_release }}/SALTSTACK-GPG-KEY.pub'
```

**Comment by aboe76** [comment]
@myii I don't know what the osmajorrelease number for rasbian is...so we need to test it.

**Comment by alxwr** [comment]
> @myii I don't know what the osmajorrelease number for rasbian is...so we need to test it.

@aboe76 It's the same as for Debian: 9

**Comment by alxwr** [comment]
> @aboe76 Does that mean we can use something like this instead?

Thanks for pointing this out! PR updated.

**Comment by myii** [comment]
@alxwr Thanks for the PR -- merged.  Appreciate the feedback, @aboe76.

**Pull request merged**
