### PR TITLE
Clean-up master.d/f_defaults.conf and add winrepo_provider

### PR DESCRIPTION
**Pull request by jbouse**
- Remove extra lines with nodegroups formatting in the master.d/f_defaults.conf jinja templating
- Add the winrepo_provider configuration to work around saltstack/salt#35993

### CODE REVIEW

**Comment by jbouse** [comment]
@gravyboat example config as in the pillar.example?

**Comment by gravyboat** [comment]
Yeah I don't see `winrepo_provider` as an option with a quick search.

**Comment by jbouse** [comment]
@gravyboat No... it's not even listed in the [default config](https://github.com/saltstack/salt/blob/develop/conf/master) but I found it mentioned in the [docs](https://docs.saltstack.com/en/latest/topics/windows/windows-package-manager.html#pygit2-gitpython-support-for-maintaining-git-repos) while trying to find a solution to get around the issue with python-pygit2 in Debian stretch/testing & Ubuntu 16.04 LTS not being compiled with HTTPS support.

**Comment by gravyboat** [comment]
Thanks.

**Pull request merged**
