### PR TITLE
Fix repo management on Debian Bullseye and newer.

### PR DESCRIPTION
**Pull request by hkbakke**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

Considering that signed-by was already the default, limiting the default repo config to Stretch and newer, there should be none. 

### Describe the changes you're proposing

See commit message. Update to modern defaults for Debian and Raspbian. Fix issue with custom repos in Bullseye.

### Pillar / config required to test the proposed changes

salt:py_ver: py3 can be removed on most Debian installs.

### Debug log showing how the proposed changes work

Repo management succeeds by default on Rasbian and Debian Bullseye.

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Review by baby-gnu — APPROVED** [review]
Looks good to me

**Comment by hkbakke** [comment]
Updated the commit subject field to hopefully fix the commitlint errors.

**Comment by myii** [comment]
@hkbakke This adjustment will make `commitlint` happy (subject starts with lowercase letter):

```diff
-fix: Make it possible to not have key_url set
+fix: make it possible to not have key_url set

-fix: Update to modern defaults for Debian family 
+fix: update to modern defaults for Debian family 
```

**Comment by hkbakke** [comment]
> -fix: Make it possible to not have key_url set

Those look identical to me?

**Comment by hkbakke** [comment]
I see that the tests fails because the key_url is not present, but that is kind of the point of this PR. Is there anything I should do here?

**Comment by myii** [comment]
> I see that the tests fails because the key_url is not present, but that is kind of the point of this PR. Is there anything I should do here?

@hkbakke That's the `map.jinja` verification files that need to be updated.  I was going to suggest that I could push a commit on top of this PR to finalise it but I just noticed that this is set up based on `hkbakke:master`, which means I won't be able to do so.  Using a [feature branch](https://guides.github.com/introduction/flow/) is better for both sides.

Let me explain what needs to be changes to finalise this PR.  The following lines need to be removed:

https://github.com/saltstack-formulas/salt-formula/blob/99b14699f3f2eedf9f01081e218c1d29112f3a88/test/integration/v3002-py3/files/_mapdata/debian-10.yaml#L45

https://github.com/saltstack-formulas/salt-formula/blob/99b14699f3f2eedf9f01081e218c1d29112f3a88/test/integration/v3002-py3/files/_mapdata/debian-9.yaml#L45

https://github.com/saltstack-formulas/salt-formula/blob/99b14699f3f2eedf9f01081e218c1d29112f3a88/test/integration/v3001-py3/files/_mapdata/debian-10.yaml#L45

https://github.com/saltstack-formulas/salt-formula/blob/99b14699f3f2eedf9f01081e218c1d29112f3a88/test/integration/v3001-py3/files/_mapdata/debian-9.yaml#L45

---

Actually, thinking about this a bit further, shouldn't Ubuntu be fixed in the same way?  I.e. These lines (and the verification files):

https://github.com/saltstack-formulas/salt-formula/blob/99b14699f3f2eedf9f01081e218c1d29112f3a88/salt/osmap.yaml#L27-L31

**Comment by hkbakke** [comment]
Thank you. I'll fix the tests on my side then. 

Regarding Ubuntu, it most likely should be fixed in the same way, but as I don't have any Ubuntu minions running I did not feel confident in changing the defaults without testing it properly myself.

**Comment by myii** [comment]
> Thank you. I'll fix the tests on my side then.
> 
> Regarding Ubuntu, it most likely should be fixed in the same way, but as I don't have any Ubuntu minions running I did not feel confident in changing the defaults without testing it properly myself.

@hkbakke You're welcome.  In fact, let's not worry about Ubuntu for now.  I need to update the CI soon to add `3004` (with a working Bullseye instance) so I can tackle Ubuntu then.  Thanks for your work here.

**Comment by hkbakke** [comment]
I have updated the tests, and also modified the description of py_ver in pillar.example.

**Review by myii — APPROVED** [review]

**Comment by myii** [comment]
@hkbakke Merged, thanks for this useful PR.
@baby-gnu Thanks for the review.

**Pull request merged**
