### PR TITLE
fix(windows): use correct `salt-minion` package name

### LINKED ISSUE #411: Windows python 3 minion package has different name in salt-winrepo-ng
In osfamilymap.yaml the salt-minion package is defined as `salt-minion` under Windows.  However, winrepo-ng defines the python 3 package as `salt-minion-py3` [here](https://github.com/saltstack/salt-winrepo-ng/blob/master/salt-minion-py3.sls).
When `py_ver` is defined as `'py3'` applying salt.minion to a Windows minion complains that `The following packages failed to install/update: salt-minion`.

Expected:
Formula should install/update `salt-minion-py3` package on Windows when `py_ver: 'py3'`.

Actual:
Formula attempts (and fails) to install/upgrade `salt-minion` package on Windows when `py_ver: 'py3'`.

To reproduce:
Install Py3 minion on Windows, apply `salt.minion` state to the minion with `py_ver: 'py3'` in `salt` pillar, observe `pkg.installed` failure with `The following packages failed to install/update: salt-minion`.

### PR DESCRIPTION
**Pull request by myii**
* From `salt-winrepo-ng`:
  - https://github.com/saltstack/salt-winrepo-ng/blob/master/salt-minion-py2.sls
  - https://github.com/saltstack/salt-winrepo-ng/blob/master/salt-minion-py3.sls
* Close #411

---

@labmonkey42 I've prepared this blindly, since I have no available Windows minions to test on.  However, I've tested it as best I can and it produces the correct packages for both `py2` and `py3`.  Will you be able to test this out to confirm it works for both?  Until then, I will keep this PR in draft status.

### CODE REVIEW

**Comment by labmonkey42** [comment]
At no point in the original report did I indicate that the py2 package in winrepo-ng was salt-master-p2.

**Comment by myii** [comment]
@labmonkey42 This PR doesn't result in `salt-master-p2`.  Can you identify where the problem is in the changeset?

**Comment by labmonkey42** [comment]
To be more clear, in my local copy I just did
```
Windows:
  {% if salt['pillar.get']('salt:py_ver', 'py2') == 'py3' -%}
  salt_minion: salt-minion-py3
  {% else -%}
  salt_minion: salt-minion
  {% endif -%}
  config_path: 'C:\salt\conf'
  minion_service: salt-minion
```
I was going to submit my own PR but got caught up with some other work the last couple of days.

**Comment by myii** [comment]
@labmonkey42 Thanks for that clarification.  The PR has been corrected to use:

* `py2`: `salt-minion`
* `py3`: `salt-minion-py3`

**Comment by labmonkey42** [comment]
Works for me, thanks!

**Comment by myii** [comment]
@labmonkey42 Appreciate you taking your time to test this.  Removed draft status from this PR.  @aboe76 Ready for merge if you're happy with this.

**Comment by aboe76** [comment]
@myii thanks for this, @labmonkey42 thanks for reviewing.

**Comment by myii** [comment]
Thanks for the merge @aboe76.

**Pull request merged**
