### PR TITLE
fix(Defaults) master_type: str

### PR DESCRIPTION
**Pull request by dth202**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Describe the changes you're proposing

Change salt:minion:master_type from 'true' to 'str' in defaults.yaml. 
The default value for the salt-minion config is str according to salt documentation, but the value in defaults.yaml is true. Setting master_type to true in the salt-minion config causes an error the salt-minion starts

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by baby-gnu** [comment]
Hello.

Could you fix the [CI errors](https://gitlab.com/saltstack-formulas/salt-formula/-/pipelines/232304958)?

**Comment by noelmcloughlin** [comment]
@dth202 could you update commit message to comply with https://www.conventionalcommits.org/en/v1.0.0/#summary

**Review by myii — APPROVED** [review]
https://docs.saltproject.io/en/latest/ref/configuration/minion.html#master-type

> Default: `str`

**Comment by myii** [comment]
Apologies for the excessive delay, @dth202 -- finally got around to reviewing and finalising this.

Thanks for the prompt, @noelmcloughlin.

**Comment by noelmcloughlin** [comment]
Thanks @myii  @dth2020

> https://docs.saltproject.io/en/latest/ref/configuration/minion.html#master-type

That page explains all valid values except "str".  What does "str" mean?

**Comment by myii** [comment]
> That page explains all valid values except "str". What does "str" mean?

@noelmcloughlin Good question, I've never changed this option myself.  Here's a little digging down.

https://github.com/saltstack/salt/pull/25703/files

* Changeset shows that the default used to be `standard` at one point.

https://github.com/saltstack/salt/blob/8ce39ddb2594358d47e24628af85a9b260ff1fe1/conf/minion#L39-L47
https://github.com/saltstack/salt/blob/8ce39ddb2594358d47e24628af85a9b260ff1fe1/conf/proxy#L61-L67

* `Multiple hot masters are configured by setting this value to "str".`

https://github.com/saltstack/salt/issues/42803

* A discussion about having multiple hot masters for HA.

**Pull request merged**
