### PR TITLE
salt-cloud handling cleanups

### PR DESCRIPTION
**Pull request by EvaSDK**
Current states leading to flapping file creation/removal when pillar declarated filenames collide with files provided in the defaults used by `file.recurse`. Since I did not want to define my own hierarchy just to solve this problem I rewrote this part of the formula to dump everything in proper order.

Also compacted the logic of `pip.installed` as it seems unnecessarily complicated to declare this many states.

### CODE REVIEW

**Comment by EvaSDK** [comment]
Actually this still leads to delete/add like output. I think it would be better to just have either `file.recurse` or `file.serialize` behavior, selectable from the pillar maybe as current status makes it scary when you see your config removed.

**Comment by aboe76** [comment]
@EvaSDK maybe something similar as the master.d and minion.d files where everything with _* is excluded from file.recurse....and ship the default cloud provider files from salt...with a _ as prefix...?

**Comment by EvaSDK** [comment]
That sounds ok to me, I'll try to add this to the PR.

**Comment by EvaSDK** [comment]
This should do it.

**Comment by aboe76** [comment]
@nmadhok would you take a look and check it out?

**Comment by aboe76** [comment]
thanks @nmadhok

**Comment by nmadhok** [comment]
Merged! Thanks @aboe76 @EvaSDK

**Comment by EvaSDK** [comment]
Thanks guys.

**Pull request merged**
