### PR TITLE
added rest_tornado to _defaults.conf

### PR DESCRIPTION
**Pull request by aboe76**
Added rest tornado configuration options to salt-master _defaults.conf

see pillar.example for configuration

### CODE REVIEW

**Comment by gravyboat** [comment]
@aboe76 Hmm, am I just missing the additions to the pillar.example? I don't see anything on your branch that uses `rest_tornado`.

**Comment by aboe76** [comment]
Ow will fix it later today

**Comment by nmadhok** [comment]
@aboe76 waiting for the changes.

**Comment by aboe76** [comment]
@nmadhok sorry needed be at work first...but got it squashed in one commit.

**Comment by nmadhok** [comment]
@aboe76 Thanks! Not a problem

**Pull request merged**
