### PR TITLE
minion: master_alive_interval: remove duplicate

### PR DESCRIPTION
**Pull request by ze42**

### CODE REVIEW

**Comment by ze42** [comment]
The following `master_alive_interval` line is also, and still present at line 98.

```
{{ get_config('master_alive_interval', '30') }}
```

**Comment by ze42** [comment]
same as #368 but also removing the associated comment.

**Comment by aboe76** [comment]
@ze42 can you rebase

**Comment by ze42** [comment]
@aboe76 properly rebased.

**Comment by aboe76** [comment]
@ze42 thanks for this

**Pull request merged**
