### PR TITLE
fix(macos): fix brew packaging handling

### PR DESCRIPTION
**Pull request by noelmcloughlin**
This PR fixes various package handling errors on MacOS when homebrew is used.

This PR also is workaround for https://github.com/saltstack/salt/issues/49348

And brew should be run as non-root user.

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
One Travis CI failure is unrelated.

**Comment by aboe76** [comment]
@noelmcloughlin I don't know where to start with merging some of this stuff..can you help figure out the order?

**Comment by noelmcloughlin** [comment]
Verified `salt.minion` state on MacOS
```
        ID: salt-minion-brew-workaround
    Function: cmd.run
        Name: /usr/local/bin/brew install salt
      Result: True
     Comment: Command "/usr/local/bin/brew install salt" run
     Started: 21:40:38.248548
    Duration: 3380.916 ms
     Changes:   
              ----------
              pid:
                  83804
              retcode:
                  0
              stderr:
                  Warning: salt 2019.2.0_1 is already installed and up-to-date
                  To reinstall 2019.2.0_1, run `brew reinstall salt`
              stdout:
----------
          ID: salt-minion
    Function: file.recurse
        Name: /private/etc/salt/minion.d
      Result: True
     Comment: The directory /private/etc/salt/minion.d is in the correct state
     Started: 21:40:41.631728
    Duration: 246.998 ms
     Changes:   
----------
          ID: salt-minion
    Function: service.running
        Name: com.saltstack.salt.minion
      Result: False
     Comment: The named service com.saltstack.salt.minion is not available
     Started: 21:40:41.882143
    Duration: 367.579 ms
     Changes:   
----------
          ID: remove-old-minion-conf-file
    Function: file.absent
        Name: /private/etc/salt/minion.d/_defaults.conf
      Result: True
     Comment: File /private/etc/salt/minion.d/_defaults.conf is not present
     Started: 21:40:42.250326
    Duration: 0.341 ms
     Changes:   
----------
          ID: salt-minion
    Function: cmd.run
        Name: exec 0>&- # close stdin
exec 1>&- # close stdout
exec 2>&- # close stderr
nohup salt-call --local service.restart com.saltstack.salt.minion --out-file /dev/null &
      Result: True
     Comment: Command "exec 0>&- # close stdin
              exec 1>&- # close stdout
              exec 2>&- # close stderr
              nohup salt-call --local service.restart com.saltstack.salt.minion --out-file /dev/null &" run
     Started: 21:40:42.250834
    Duration: 5.476 ms
     Changes:   
              ----------
              pid:
                  84417
              retcode:
                  0
              stderr:
              stdout:

Summary for local
------------
Succeeded: 4 (changed=2)
Failed:    1
------------
```

**Comment by noelmcloughlin** [comment]
> I don't know where to start with merging some of this stuff..can you help figure out the order?

Hi @aboe76 I think PR's are not conflicting. 
This package handling issue was discussed in [Slack](https://saltstackcommunity.slack.com/archives/C8VH92RJT/p1564585850004200) but I got hit by https://github.com/saltstack/salt/issues/49348 too - seems to be working now on MacOS.

I guess `service.running` needs to be addressed too in future PR.

**Comment by noelmcloughlin** [comment]
Retested on MacOS.
```
          ID: download-salt-minion
    Function: cmd.run
        Name: /usr/local/bin/brew install salt
      Result: True
     Comment: Command "/usr/local/bin/brew install salt" run
     Started: 01:32:02.552883
    Duration: 3396.716 ms
     Changes:   
              ----------
              pid:
                  12207
              retcode:
                  0
              stderr:
                  Warning: salt 2019.2.0_1 is already installed and up-to-date
                  To reinstall 2019.2.0_1, run `brew reinstall salt`
              stdout:
----------
          ID: salt-minion
    Function: file.recurse
        Name: /private/etc/salt/minion.d
      Result: True
     Comment: The directory /private/etc/salt/minion.d is in the correct state
     Started: 01:32:05.952743
    Duration: 262.306 ms
     Changes:   
----------
          ID: salt-minion
    Function: service.running
        Name: com.saltstack.salt.minion
      Result: False
     Comment: The named service com.saltstack.salt.minion is not available
     Started: 01:32:06.218350
    Duration: 414.51 ms
     Changes:   
----------
          ID: remove-old-minion-conf-file
    Function: file.absent
        Name: /private/etc/salt/minion.d/_defaults.conf
      Result: True
     Comment: File /private/etc/salt/minion.d/_defaults.conf is not present
     Started: 01:32:06.633470
    Duration: 0.344 ms
     Changes:   
----------
          ID: salt-minion
    Function: cmd.run
        Name: exec 0>&- # close stdin
exec 1>&- # close stdout
exec 2>&- # close stderr
nohup salt-call --local service.restart com.saltstack.salt.minion --out-file /dev/null &
      Result: True
     Comment: Command "exec 0>&- # close stdin
              exec 1>&- # close stdout
              exec 2>&- # close stderr
              nohup salt-call --local service.restart com.saltstack.salt.minion --out-file /dev/null &" run
     Started: 01:32:06.633996
    Duration: 5.385 ms
     Changes:   
              ----------
              pid:
                  12808
              retcode:
                  0
              stderr:
              stdout:
----------
          ID: remove-macpackage-salt
    Function: file.absent
        Name: /tmp/salt.pkg
      Result: True
     Comment: File /tmp/salt.pkg is not present
     Started: 01:32:06.639697
    Duration: 0.572 ms
     Changes:   

Summary for local
------------
Succeeded: 5 (changed=2)
Failed:    1
------------
Total states run:     6
Total run time:   4.080 s
```

**Comment by noelmcloughlin** [comment]
This PR does not fix #352 because macpackage handling is [completely broken and untestable ](https://github.com/saltstack-formulas/salt-formula/issues/352#issuecomment-517076049). This PR does fixup minion.sls so macpackage use case can be tested (but it does not work). This PR addresses homebrew (not macpackage issues in #352).

**Comment by noelmcloughlin** [comment]
Added [commit](https://github.com/saltstack-formulas/salt-formula/pull/426/commits/beb0e85b0436e1f3475e351f1b23a73f1e41fc72)  to fix `formulas.sls` state on MacOS/FreeBSD.  Verified on MacOS.

**Pull request merged**
