### PR TITLE
fix(minion): Fix version compare in minion.sls

### PR DESCRIPTION
**Pull request by sticky-note**

### CODE REVIEW

**Comment by daks** [comment]
LGTM too, but Salt versions < 2017 are not supported anymore (cf https://s.saltstack.com/product-support-lifecycle/) so I think this patch is not useful.

**Comment by sticky-note** [comment]
So we can remove this entire test.
Without this patch, and with 2019.2.0, we are matching to the

**Comment by sticky-note** [comment]
@myii @noelmcloughlin. I'll close this when https://github.com/saltstack-formulas/salt-formula/pull/416 get merged but if i'll take time, can we merge this and rebase https://github.com/saltstack-formulas/salt-formula/pull/416 with this modification ?

**Comment by noelmcloughlin** [comment]
This is approved - Yes we should merge - comments can be addressed in #416

**Comment by myii** [comment]
@sticky-note Let's improve this implementation and get this merged:

```diff
-  {%- if grains['saltversioninfo'][0] >= 2016 and grains['saltversioninfo'][1] >= 3 %}
+  {%- if grains['saltversioninfo'] > [2016, 3] %}
```

CC: @noelmcloughlin @daks.

**Comment by daks** [comment]
> @sticky-note Let's improve this implementation and get this merged:
> 
> ```diff
> -  {%- if grains['saltversioninfo'][0] >= 2016 and grains['saltversioninfo'][1] >= 3 %}
> +  {%- if grains['saltversioninfo'] > [2016, 3] %}
> ```
> 
> CC: @noelmcloughlin @daks.

Do we want to support Salt < 2017? which itself is not supported par Saltstack itself?
If not, then no need to make any verification.

**Comment by myii** [comment]
@daks I've actually removed the verification in #416 but that is stuck for merging right now.  Others want this PR merged so I'm suggesting a cleaner solution for the meantime, even though it references older Salt versions for the time being.

**Comment by sticky-note** [comment]
> supported par Saltstack

@daks You es French ^^

@myii I've left the `>=` operator because we want `2016.3.0` to be matched by the test.
Is `grains['saltversioninfo'] >= [ 2016, 3 ]` equivalent with `grains['saltversioninfo'][0] >= 2016 and grains['saltversioninfo'][1] >= 3`

**Comment by myii** [comment]
@sticky-note The following is sufficient by itself, no need for the `2017` clause:

```diff
-  {%- if grains['saltversioninfo'][0] >= 2017
-      or grains['saltversioninfo'] >= [ 2016, 3 ] %}
+  {%- if grains['saltversioninfo'] >= [2016, 3] %}
```

**Comment by sticky-note** [comment]
The PR is about that 
-> version `2018.2.0` don't enter in the the condition `grains['saltversioninfo'][0] >= 2016 and grains['saltversioninfo'][1] >= 3`  because `grains['saltversioninfo'][1]` is less than `3`. It is why i put this first condition.

**Comment by myii** [comment]
> The PR is about that
> -> version `2019.2.0` don't enter in the the condition `grains['saltversioninfo'][0] >= 2016 and grains['saltversioninfo'][1] >= 3` because `grains['saltversioninfo'][1]` is less than `3`. It is why i put this first condition.

Forget the old method and try this _by itself_:

```jinja
{%- if grains['saltversioninfo'] >= [2016, 3] %}
```

You'll find it works for `2019.2`, etc.

**Comment by daks** [comment]
@myii ok then.

@sticky-note yes, why?

**Pull request merged**
