### PR TITLE
Pillar example: Fix duplicate master keys

### PR DESCRIPTION
**Pull request by tony**
Causing issues with sls rendering on vagrant boxes.

Comment out multi-master keys.

### CODE REVIEW

**Comment by babilen** [comment]
The `pillar.example` file is, well, an example and shouldn't necessarily be used as-is in your setup. The main idea is to document all, even contradictory, settings that are supported by this formula.

How exactly does this causes issue with vagrant boxes?

**Comment by tony** [comment]
https://github.com/saltstack-formulas/salt-formula/blob/master/dev/setup-salt.sh#L8

If you type ``vagrant up`` and ``vagrant ssh`` into the box, there will be an error connecting to master.

**Comment by tony** [comment]
I'm sure the intention is for the example to edited, however, sometimes the intuition is to dig right in and ``vagrant up``. And the ``setup-salt.sh`` leads me to believe that was the intention from the start.  Just because it's an example doesn't mean it can't work out of the box.

**Comment by babilen** [comment]
That's just, well, unfortunate. @MSeven: Do you assume that `pillar.example` is always usable as-is ?

**Comment by iggy** [comment]
pillar.example is likely going the way of the dodo in some formulas (at least in the form it's in now). The more formulas we move to a defaults.yaml with merging type setup, the less the pillar.example will be useful (it's generally been a sort of document of the defaults with some other bits thrown in to show less obvious examples). I have plans of getting rid of the pillar.example in some formulas all together (in favor or documenting the expected tunables in the actual README).

I can name a number of formulas that don't have a usable pillar.example out of the box.

Isn't there a bug open about changing how this formula handles vagrant testing?

**Comment by babilen** [comment]
Yeah, I agree with @iggy. `pillar.example` was, and is, meant to serve as documentation, but that purpose if probably better served by including it in the `README`. fwiw, I think that this formula should simply define whatever data it needs for testing explicitly rather than relying on a working `pillar.example`.

**Comment by tony** [comment]
Got it. 

> I think that this formula should simply define whatever data define whatever data it needs for testing explicitly

If what you mean is we could have ``vagrant up`` with the minimal necessary pillar data pre-seeded with default variables, then +1.

The data layout for pillars is something that can get complicated. Relatively speaking, this is sophisticated pillar -> sls config mapping. Let's keep in mind that, particularly for those who aren't acclimated with this project yet.

**Comment by babilen** [comment]
> If what you mean is we could have vagrant up with the minimal necessary pillar data pre-seeded with default variables, then +1.
That is exactly what I had in mind. I'm simply not sure what @MSeven requires there.

**Comment by MSeven** [comment]
My Original understanding of the Formula documentation was, that Formulas have to be able to run without any extra pillar data (http://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#usage) and that the pillar.example should document the used default config, while also illustrating available options (http://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#pillar-overrides).

So, well yes, i assumed the pillar.example would always be the usable default configuration, that then could be extended and enhanced for testing purposes.

TBH. I didn't anticipate this problem at all. Copying the pillar example over was mainly meant to give users an easily changed template of available options.

**Pull request closed without merging**
