### PR TITLE
fix(jinja): replace version_cmp with grains lookup

### LINKED ISSUE #459: [BUG] OrderedDict object has no attribute 'version_cmp'
### Formula commit hash / release tag

Master

### Versions reports (master & minion)
```
(base) OCIR-LM20540:salt-formula nmcloughlin$ salt --versions-report
/usr/local/Cellar/salt/3000/libexec/lib/python3.7/site-packages/salt/ext/tornado/httputil.py:107: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  class HTTPHeaders(collections.MutableMapping):
Salt Version:
           Salt: 3000
 
Dependency Versions:
           cffi: 1.13.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.3
        libgit2: 0.28.4
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.28.2
         Python: 3.7.7 (default, Mar 10 2020, 15:43:03)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.1.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 18.7.0
         system: Darwin
        version: 10.14.6 x86_64
```

### Pillar / config used
---

### Describe the bug
This is the bug output

```
    Rendering SLS 'base:salt.formulas' failed: Jinja variable 
      'salt.utils.odict.OrderedDict object' has no attribute 'version_cmp'
```

This is the SLS part..
```
formulas.sls:    - parallel: {{ salt.pkg.version_cmp(grains['saltversion'], '2017.7.0') >= 0 }}
```

### Steps to reproduce the bug
Running on macOS, python 3.7.3

### Expected behaviour
No bug

### PR DESCRIPTION
**Pull request by noelmcloughlin**
### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [x] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests
Fixes #459 

### Describe the changes you're proposing

Use `grains`, more portable anyway

### Pillar / config required to test the proposed changes

```
salt_formulas:
  git_opts:
    default:
      baseurl: https://github.com/saltstack-formulas
         {%- if grains['kernel'] in ['FreeBSD', 'OpenBSD', 'NetBSD'] %}
      basedir: /usr/local/etc/salt/states/namespaces/saltstack-formulas
         {%- else %}
      basedir: /srv/salt/namespaces/saltstack-formulas
         {%- endif %}
  basedir_opts:
    makedirs: True
    user: root
      {%- if grains['kernel'] in ['FreeBSD', 'OpenBSD', 'NetBSD'] %}
    group: wheel
      {%- else %}
    group: root
      {%- endif %}
    mode: 755
  minion_conf:
    create_from_list: True
  list:
    base:
     {{ '- epel-formula' if grains.os_family in ('RedHat',) else '' }}
     - salt-formula
```

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [x] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by myii** [comment]
@noelmcloughlin Thanks for this PR, please also include the change for `pkg.version_cmp` here:

https://github.com/saltstack-formulas/salt-formula/blob/b7d323f878860f3a9b8cdaed5f09ea23e283f316/salt/formulas.sls#L57

**Comment by noelmcloughlin** [comment]
Added commit to failed Suse travis job
```
     ✔  System Package salt-master version is expected to eq "2019.2.0-lp151.5.12.1"
     ✔  System Package salt-minion is expected to be installed
     ✔  System Package salt-minion version is expected to eq "2019.2.0-lp151.5.12.1"
```

**Comment by noelmcloughlin** [comment]
> @noelmcloughlin Thanks for this PR, please also include the change for `pkg.version_cmp` here:

Thanks @myii, I added commit to fix that line.

**Comment by myii** [comment]
Closes #459.

**Comment by myii** [comment]
Merged, thanks @noelmcloughlin.

**Comment by noelmcloughlin** [comment]
Thanks, @myii  much appreicated.

**Pull request merged**
