### PR TITLE
refactor(kitchen+travis+inspec): use pre-salted images

### PR DESCRIPTION
**Pull request by myii**
* Semi-automated using https://github.com/myii/ssf-formula/pull/36
* Restructure all tests according to updated test suites
* Improve tests where necessary (code style, new platforms and package versions)

Also includes:

* fix(pkgrepo): fix settings for `opensuse`
  - Wouldn't import the repo without `gpgautoimport: true`
* fix(pkgrepo): provide settings for `amazon`

### CODE REVIEW

**Comment by daks** [comment]
looks fine for me. Just one question: can it be considered a 'refactor'? because mostly it touches only tests.

**Comment by myii** [comment]
> ... Just one question: can it be considered a 'refactor'? because mostly it touches only tests.

@daks `ci`, `test`, files being moved around, nothing new, nothing removed => `refactor` seemed the most appropriate.  Actually, it's because I'd usually split this into separate commits but a lot gets done in one commit via. `ssf-formula`.

**Comment by daks** [comment]
ok then

**Comment by myii** [comment]
@daks Can we get this merged?  There are few active PRs on `salt-formula` at the moment and every time a change is made, it blocks other Travis runs for almost half an hour.

**Pull request merged**
