### PR TITLE
Add mine_functions to master config template

### PR DESCRIPTION
**Pull request by jcftang**
Add 'mine_functions' into master's configuration template

### CODE REVIEW

**Comment by iggy** [comment]
Umm... nope.

"To enable the Salt Mine the mine_functions option needs to be applied to a minion. This option can be applied via the minion's configuration file, or the minion's Pillar."

**Comment by jcftang** [comment]
Good point, it should be moved to the minion section

**Comment by jcftang** [comment]
There is a seperate PR for this already at https://github.com/saltstack-formulas/salt-formula/pull/28

**Comment by nmadhok** [comment]
@iggy thanks for the catch. I have reverted the PR

**Pull request merged**
