### PR TITLE
adding salt-minion restart option from official FAQ page

### PR DESCRIPTION
**Pull request by mechleg**
I have run into an issue similar to those described in #136 .  I was hoping to find a different solution then the one recently merged, mostly to not have another package dependency.

I found such a solution here, using the "bg" option in cmd.run:
https://docs.saltstack.com/en/latest/faq.html#what-is-the-best-way-to-restart-a-salt-minion-daemon-using-salt-after-upgrade

This has been working on all my Linux minions better then the salt-minion restart method used in the current formula.  It should also work on Windows though I am not able to test that.

This PR changes the current default salt-minion restart behavior to that described in the linked FAQ.  It should be backward compatible and add similar functionality to salt versions without the "bg" option.

Thoughts?  Good idea?  Bad idea?

### CODE REVIEW

**Comment by aboe76** [comment]
@tlemarchand could you take a look to?

**Comment by javierbertoli** [comment]
It LGTM, although I have no Windows box to test the Windows parts.

**Comment by aboe76** [comment]
@mechleg can you confirm this works on windows? @javierbertoli and I don't have a setup with windows minions.

**Comment by mechleg** [comment]
Unfortunately, neither do I, Linux only shop over here.  

I figured since it was on the FAQ, someone tested those commands in Windows at some point.  If no one uses this formula with Windows, I could take those bits out.

**Comment by aboe76** [comment]
@mechleg and @javierbertoli because this is behind a switch I think it's safe to merge and if some windows minion user is complaining we can fix it then.

**Comment by mechleg** [comment]
Sounds good to me, anything else I need to do?

**Comment by aboe76** [comment]
@mechleg no, just need a confirmation from @javierbertoli then I merged it.

**Comment by javierbertoli** [comment]
@aboe76, I think it's ok to merge.

**Comment by aboe76** [comment]
@mechleg and @javierbertoli thanks for this. hopefully it will help others.

**Pull request merged**
