### PR TITLE
feat(formulas): git.latest parallelization

### PR DESCRIPTION
**Pull request by sticky-note**
A little tweak of my last PR https://github.com/saltstack-formulas/salt-formula/pull/418 to get job done in parrallel.
Improve speed!

### CODE REVIEW

**Comment by aboe76** [comment]
@myii nice work

**Comment by myii** [comment]
@aboe76 Actually, it was @sticky-note!

**Comment by myii** [comment]
@sticky-note The use of `pkg.version_cmp` has caused a regression, such as on MacOS and Windows, see https://github.com/saltstack-formulas/salt-formula/issues/459#issuecomment-601167591.

A fix has been proposed at #460.

**Comment by daks** [comment]
I'm curious, where does this `parallel` keyword come from, is it documented somewhere and what does it do?

**Comment by myii** [comment]
> I'm curious, where does this `parallel` keyword come from, is it documented somewhere and what does it do?

@daks See https://docs.saltstack.com/en/latest/ref/states/parallel.html.  In this case, it will pull multiple repos at the same time.

**Comment by daks** [comment]
good to discover it, thanks :)

**Pull request merged**
