### PR TITLE
Install latest stable version of Salt

### PR DESCRIPTION
**Pull request by djibi2**
Use the salt bootstrap method to install salt.  The current method yields old versions of salt:

```
sudo salt '*' test.versions_report
salt:
               Salt: 0.17.5
             Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
             Jinja2: 2.7.2
           M2Crypto: 0.21.1
     msgpack-python: 0.3.0
       msgpack-pure: Not Installed
           pycrypto: 2.6.1
             PyYAML: 3.10
              PyZMQ: 14.0.1
                ZMQ: 4.0.4

```
With this change in places, the resulting versions are:

> salt:
>     Salt Version:
>                Salt: 2015.8.8.2
>      
>     Dependency Versions:
>              Jinja2: 2.7.2
>            M2Crypto: Not Installed
>                Mako: 0.9.1
>              PyYAML: 3.10
>               PyZMQ: 14.0.1
>              Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
>                RAET: Not Installed
>             Tornado: 4.2.1
>                 ZMQ: 4.0.4
>                cffi: Not Installed
>            cherrypy: Not Installed
>            dateutil: 1.5
>               gitdb: 0.5.4
>           gitpython: 0.3.2 RC1
>               ioflo: Not Installed
>             libgit2: Not Installed
>             libnacl: Not Installed
>        msgpack-pure: Not Installed
>      msgpack-python: 0.3.0
>        mysql-python: 1.2.3
>           pycparser: Not Installed
>            pycrypto: 2.6.1
>              pygit2: Not Installed
> 
>         PyZMQ: 14.0.1
>              Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
>                RAET: Not Installed
>             Tornado: 4.2.1
>                 ZMQ: 4.0.4
>                cffi: Not Installed
>            cherrypy: Not Installed
>            dateutil: 1.5
>               gitdb: 0.5.4
>           gitpython: 0.3.2 RC1
>               ioflo: Not Installed
>             libgit2: Not Installed
>             libnacl: Not Installed
>        msgpack-pure: Not Installed
>      msgpack-python: 0.3.0
>        mysql-python: 1.2.3
>           pycparser: Not Installed
>            pycrypto: 2.6.1
>              pygit2: Not Installed
>        python-gnupg: Not Installed
>               smmap: 0.8.2
>             timelib: Not Installed
>        System Versions:
>                dist: Ubuntu 14.04 trusty
>             machine: x86_64
>             release: 3.13.0-83-generic
>              system: Ubuntu 14.04 trusty
>

### CODE REVIEW

**Comment by gravyboat** [comment]
Could you please rebase?

**Comment by gravyboat** [comment]
Or close if you think: https://github.com/saltstack-formulas/salt-formula/pull/219 resolves it.

**Comment by djibi2** [comment]
This was resolved by #219

**Comment by gravyboat** [comment]
Okay then I will close this, thanks!

**Pull request closed without merging**
