### PR TITLE
update 2015.8.7 version config for the minion

### PR DESCRIPTION
**Pull request by aboe76**
Updated the minion config f_defaults.conf, 
Reverted the removal of the comments so new users can see and use these.

### CODE REVIEW

**Comment by gravyboat** [comment]
Thanks for this one. We should look at adding all of these to the example at some point I imagine, I just don't want to do it since there are so many. :(

**Comment by aboe76** [comment]
yes, I was thinking about that too, but that will make the pillar.example a bit crowded

**Comment by nmadhok** [comment]
@aboe76 @gravyboat Accidentally merged this one. Didn't know you two were already discussing over this. Do you want me to revert it?

**Comment by aboe76** [comment]
@nmadhok no need, thanks for merging.

**Comment by gravyboat** [comment]
@nmadhok I actually meant to merge it so no problem at all. :+1:

**Pull request merged**
