### PR TITLE
Add modules to install gitfs backend dependencies

### PR DESCRIPTION
**Pull request by iggy**
Add modules for gitfs dependencies and documentation for how to use them.

### CODE REVIEW

**Comment by gravyboat** [comment]
Looks good to me.

**Comment by nmadhok** [comment]
@gravyboat There's nothing in the else block. There will be a jinja error.

**Comment by gravyboat** [comment]
@nmadhok Damn you're absolutely right, I missed that one. @iggy do you want to trash that else for now?

**Comment by iggy** [comment]
I installed all of these and didn't get jinja errors.

**Comment by iggy** [comment]
I'm assuming it's because (as lame as it is), a comment still counts as something.

**Comment by nmadhok** [comment]
I would suggest removing those else blocks till the time when you actually add installing from package code. Open an issue for reference.

**Comment by iggy** [comment]
I left it there hoping someone would see it and tell me their distro had the packages so I'd know what to test with. But I'm not terribly concerned either way. I'll send in a follow up patch shortly. Someone is giving me the "let's go already look".

**Comment by gravyboat** [comment]
@iggy At your work? If so, give them the 'this is not ready' look. Or just tell them you're the salt master and they know nothing!

**Comment by nmadhok** [comment]
No rush. Thanks @iggy!

**Pull request merged**
