### PR TITLE
fix(windows): various fixes

### LINKED ISSUE #485: [BUG] formulas state fails on Windows
### Pillar / config used

---

### Describe the bug

I was running salt-formula/init.sls and there are many state failures on Windows which need investigation. 

Log attached.

### PR DESCRIPTION
**Pull request by noelmcloughlin**
### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [x] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

Related to one failed state in #485 
Fix #485 

### Describe the changes you're proposing

This PR prevents running the master state on Windows

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
Resolves #485 (except one git issue)

**Comment by noelmcloughlin** [comment]
Windows output for `salt.formulas` state:
```
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas
    Function: file.directory
      Result: True
     Comment: The directory c:\salt\srv\salt\namespaces\saltstack-formulas is in the correct state
     Started: 23:28:45.604000
    Duration: 7.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/salt-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/salt-formula.git
      Result: False
     Comment: Unable to get position of local branch 'master': fatal: ambiguous argument 'master^commit': unknown revision or path not in the working tree.
              Use '--' to separate paths from revisions, like this:
              'git <command> [<revision>...] -- [<file>...]'
     Started: 23:28:45.657000
    Duration: 1037.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/openssh-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/openssh-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/openssh-formula is up-to-date
     Started: 23:28:46.694000
    Duration: 2065.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/packages-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/packages-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/packages-formula is up-to-date
     Started: 23:28:48.760000
    Duration: 1752.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/firewalld-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/firewalld-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/firewalld-formula is up-to-date
     Started: 23:28:50.512000
    Duration: 1738.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/eclipse-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/eclipse-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/eclipse-formula is up-to-date
     Started: 23:28:52.250000
    Duration: 1723.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/tomcat-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/tomcat-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/tomcat-formula is up-to-date
     Started: 23:28:53.973000
    Duration: 2384.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/sqlplus-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/sqlplus-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/sqlplus-formula is up-to-date
     Started: 23:28:56.357000
    Duration: 1781.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/sqldeveloper-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/sqldeveloper-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/sqldeveloper-formula is up-to-date
     Started: 23:28:58.138000
    Duration: 1769.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/sun-java-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/sun-java-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/sun-java-formula is up-to-date
     Started: 23:28:59.907000
    Duration: 1752.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/java-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/java-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/java-formula is up-to-date
     Started: 23:29:01.659000
    Duration: 1734.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/users-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/users-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/users-formula is up-to-date
     Started: 23:29:03.393000
    Duration: 1929.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/kubernetes-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/kubernetes-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/kubernetes-formula is up-to-date
     Started: 23:29:05.322000
    Duration: 1858.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/cloudfoundry-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/cloudfoundry-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/cloudfoundry-formula is up-to-date
     Started: 23:29:07.180000
    Duration: 2082.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/postgres-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/postgres-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/postgres-formula is up-to-date
     Started: 23:29:09.262000
    Duration: 1923.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/jetbrains-intellij-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/jetbrains-intellij-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/jetbrains-intellij-formula is up-to-date
     Started: 23:29:11.185000
    Duration: 1781.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/jetbrains-pycharm-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/jetbrains-pycharm-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/jetbrains-pycharm-formula is up-to-date
     Started: 23:29:12.967000
    Duration: 1750.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/etcd-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/etcd-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/etcd-formula is up-to-date
     Started: 23:29:14.718000
    Duration: 2058.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/ceph-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/ceph-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/ceph-formula is up-to-date
     Started: 23:29:16.776000
    Duration: 4469.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/deepsea-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/deepsea-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/deepsea-formula is up-to-date
     Started: 23:29:21.245000
    Duration: 5206.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/docker-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/docker-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/docker-formula is up-to-date
     Started: 23:29:26.451000
    Duration: 13575.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/helm-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/helm-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/helm-formula is up-to-date
     Started: 23:29:40.027000
    Duration: 5853.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/iscsi-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/iscsi-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/iscsi-formula is up-to-date
     Started: 23:29:45.880000
    Duration: 6947.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/lvm-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/lvm-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/lvm-formula is up-to-date
     Started: 23:29:52.827000
    Duration: 7453.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/devstack-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/devstack-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/devstack-formula is up-to-date
     Started: 23:30:00.280000
    Duration: 9031.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/golang-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/golang-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/golang-formula is up-to-date
     Started: 23:30:09.311000
    Duration: 6661.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/memcached-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/memcached-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/memcached-formula is up-to-date
     Started: 23:30:15.972000
    Duration: 10745.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/opensds-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/opensds-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/opensds-formula is up-to-date
     Started: 23:30:26.717000
    Duration: 6675.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/mysql-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/mysql-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/mysql-formula is up-to-date
     Started: 23:30:33.393000
    Duration: 7096.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/timezone-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/timezone-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/timezone-formula is up-to-date
     Started: 23:30:40.489000
    Duration: 8588.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/resolver-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/resolver-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/resolver-formula is up-to-date
     Started: 23:30:49.078000
    Duration: 7346.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/nginx-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/nginx-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/nginx-formula is up-to-date
     Started: 23:30:56.424000
    Duration: 7894.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/mongodb-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/mongodb-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/mongodb-formula is up-to-date
     Started: 23:31:04.318000
    Duration: 6200.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/apache-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/apache-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/apache-formula is up-to-date
     Started: 23:31:10.518000
    Duration: 6535.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/prometheus-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/prometheus-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/prometheus-formula is up-to-date
     Started: 23:31:17.054000
    Duration: 4412.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/grafana-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/grafana-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/grafana-formula is up-to-date
     Started: 23:31:21.466000
    Duration: 9401.0 ms
     Changes:
----------
          ID: c:\salt\srv\salt\namespaces\saltstack-formulas/sysstat-formula_base
    Function: git.latest
        Name: https://github.com/saltstack-formulas/sysstat-formula.git
      Result: True
     Comment: Repository c:\salt\srv\salt\namespaces\saltstack-formulas/sysstat-formula is up-to-date
     Started: 23:31:30.867000
    Duration: 8317.0 ms
     Changes:

Summary for local
-------------
Succeeded: 36
Failed:     1
-------------
Total states run:     37
```

**Comment by noelmcloughlin** [comment]
Resolves #485

**Comment by myii** [comment]
Merged, thanks for the fix @noelmcloughlin.

**Pull request merged**
