### PR TITLE
Add mine_functions section to minion config

### PR DESCRIPTION
**Pull request by tmandry**
See http://docs.saltstack.com/topics/mine/ for details.

I needed this in order to use the [hostsfile-formula](https://github.com/saltstack-formulas/hostsfile-formula).

### CODE REVIEW

**Comment by jcftang** [comment]
@nmadhok given that https://github.com/saltstack-formulas/salt-formula/pull/91 got reverted due to my mistake, is there a possibility of getting this merged? is there something fundamentally broken with this PR?

**Comment by iggy** [comment]
A. It contains merge conflicts
B. You are putting something in a pillar to then have it loaded into a config file when it can be read from the pillar to begin with

**Comment by nmadhok** [comment]
@jcftang Like @iggy mentioned in a comment above, this PR contains merge conflicts and you need to resolve the merge conflicts first so I can consider it further.

**Comment by jcftang** [comment]
Ok, it feels like it's better to note to the user it is better to put this config into the minion pillar first before trying to resolve the conflict. I'm adding a link here to the documentation -- http://docs.saltstack.com/en/latest/topics/mine/#mine-functions

**Comment by aboe76** [comment]
Only thing that can be set only in the minion config is the mine interval
the mine_interval must be set in the minion’s runtime config. 
The configuration option is ignored in grains or pillar data.

**Pull request closed without merging**
